### ISSUE TITLE
One little problem with one parameter

### ISSUE THREAD

**Issue by Stargazer32584** [nrwiersma/ConfigManager#98] opened 2020-11-11 15:16 UTC
Hi,

my project with an esp32 and a ble - scanner is almost ready to run.

But i have one problem with one parameter. In my case, it is a problem with a char - array from the UI of the ConfigManager.
I convert it to an int with :  int zahl = atoi(rssimac1); .

The BLE - Libary uses a class an in this class, i use an if - request. If the scanner scans a known MAC and the RSSI of it, the esp looks to the rssi value from the ConfigManager and decide " Yes, it is a known adress" or not.

The parameter of the mac are okay. He reads this from the configmanager. But the rssi is again zero.

A serial.print in the loop shows the correct value. That's the problem i have.
Before i used your Manage, i had the INIWifimanager. But it was not mine.
Therefore, i want to use your Libary. The code is experimental and i must clean it up.

Here is my code:

`include "ConfigManager.h"
#include <HTTPClient.h>
#include <WebServer.h>
#include <ArduinoOTA.h>
#include <SPIFFS.h>
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEScan.h>
#include <BLEAdvertisedDevice.h>
#include <BLEAddress.h>
#include <Ticker.h>
#include <NTPClient.h>
#include <WiFiUdp.h>

#define DEBUGGING                     // Einkommentieren für die Serielle Ausgabe

#ifdef DEBUGGING
#define DEBUG_B(...) Serial.begin(__VA_ARGS__)
#define DEBUG_P(...) Serial.println(__VA_ARGS__)
#define DEBUG_F(...) Serial.printf(__VA_ARGS__)
#else
#define DEBUG_B(...)
#define DEBUG_P(...)
#define DEBUG_F(...)
#endif

WebServer server(80);

const char *settingsHTML = (char *)"/settings.html";
const char *stylesCSS = (char *)"/styles.css";
const char *mainJS = (char *)"/main.js";

struct Config {
  char tageins_name[32];
  char tagzwei_name[32];
  char uuideins_name[50];
  char uuidzwei_name[50];
  char rssi_werttageins[4];
  char rssi_werttagzwei[4];
  char rssi_wertibeacon[4];
  char webhook_ein[40];
  char webhook_aus[40];
  int8_t led;
  bool enabled;
} config;

struct Metadata {
  int8_t version;
} meta;

ConfigManager configManager;

///////////////////////////////////////Variablen werden aus dem ConfigManager - struct extrahiert////////////////////////////////
char* mac1 = config.tageins_name;
char* mac2 = config.tagzwei_name;
char* ibeacon1 = config.uuideins_name;
char* ibeacon2 = config.uuidzwei_name;
char* rssimac1 = config.rssi_werttageins;
char* rssimac2 = config.rssi_werttagzwei;
char* rssiibeacon = config.rssi_wertibeacon;
char* WebhookEin = config.webhook_ein;
char* WebhookAus = config.webhook_aus;
int led = config.led;
int version = meta.version;
int zahl = atoi(rssimac1);

void APCallback(WebServer *server) {
  server->on("/styles.css", HTTPMethod::HTTP_GET, [server]() {
    configManager.streamFile(stylesCSS, mimeCSS);
  });

  DebugPrintln(F("AP Mode Enabled. You can call other functions that should run after a mode is enabled ... "));
}

void APICallback(WebServer *server) {
  server->on("/disconnect", HTTPMethod::HTTP_GET, [server]() {
    configManager.clearWifiSettings(false);
  });

  server->on("/settings.html", HTTPMethod::HTTP_GET, [server]() {
    configManager.streamFile(settingsHTML, mimeHTML);
  });

  // NOTE: css/js can be embedded in a single page HTML
  server->on("/styles.css", HTTPMethod::HTTP_GET, [server]() {
    configManager.streamFile(stylesCSS, mimeCSS);
  });

  server->on("/main.js", HTTPMethod::HTTP_GET, [server]() {
    configManager.streamFile(mainJS, mimeJS);
  });

  server->on("/reboot", HTTPMethod::HTTP_GET, [server]() {
    ESP.restart();
  });

}

String IDadresseSW = "88bdf79f-59ec-4f47-bf82-39b957c568a";  //UUID SmartWatch
int RelaisPin = 32;                 // Pin an dem Relais hängt
int Verzoegerung = 15;              // Auschaltverzögerung wenn das Signal von BLE ibeacon fehlt
int active_low = 1;                 //  "0" Relais schaltet bei +5V, "1" Relais beim schaltet bei 0V
int Webhook3;
int Webhook4;
int TuerAUFUUID1;
int TuerAUFSWUUID;
boolean variable = true;
int AktuelleZeit;
int LEDGruen = 18;
int LEDRot = 19;
int LEDWeiss = 23;
int Buzzer = 16;
int Hilfsschalter;
int Anwesend;
int MillisFaktor = 1000;
int Anwesendheitspause = 60;
int Schaltpause;
String Scanne;
String Scanne2;
String wsrssi;
String wsrssi2;
int i = 0;
int MACScan;
int MACAktuell;

//Variablenblock für die Speicherung der Adressen
int MACJetzt;
int MACVor1Min;
int MACVor2Min;
int MACVor3Min;
int MACVor4Min;
int MACVor5Min;
int MACVor6Min;
int MACVor7Min;
int MACVor8Min;
int MACVor9Min;
//Stringzuordnung
String MACTendenz;

const long utcOffsetInSeconds = 3600;
char daysOfTheWeek[7][12] = {"Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"};
WiFiUDP ntpUDP;
NTPClient timeClient(ntpUDP, "pool.ntp.org", utcOffsetInSeconds);

//Millis wird gesetzt
long previousMillis = 0;
long interval = 1200;

int VerzoegerungZaeler = 0;
Ticker Tic;
static BLEAddress *pServerAddress;
static BLEAddress *pServerAddress2;
static BLEAddress *pServerAddress3;
static BLEAddress *pServerAddress4;
static BLEAddress *pServerAddress5;
BLEScan* pBLEScan ;
int scanTime = 1; //In seconds

  class MyAdvertisedDeviceCallbacks: public BLEAdvertisedDeviceCallbacks
  {
    void onResult(BLEAdvertisedDevice advertisedDevice) // passiert wenn BLE Device ( beacon ) gefunden wurde
    {

      Serial.print("iBeacon gefunden : ");
      Serial.println(advertisedDevice.toString().c_str()); // ibeacon Adresse anzeigen
      Serial.printf("   RSSI: %d ", advertisedDevice.getRSSI());
      Scanne = (advertisedDevice.toString().c_str());
      wsrssi = (advertisedDevice.getRSSI());

      ///////////////////////////////////////Testcode//////////////////////////////////////
        Serial.println("-------------------------------------");
        Serial.println("MAC von G-Tag 1 :");
        Serial.println(mac1);
        Serial.println("-------------------------------------");

        Serial.print("Schaltentfernung G-Tag 1 :");
        Serial.println(zahl);
        Serial.println("-------------------------------------");
        Serial.print("Webhook - Einschaltbefehl :");
        Serial.println(WebhookEin);
        Serial.println("-------------------------------------");
        delay(500);
        /////////////////////////////////////////////////////////////////////////////////////

  }
};

        

//Scanne2 = (advertisedDevice.toString().c_str());
//wsrssi2 = (advertisedDevice.getRSSI());

/*
  i++;
  //Codeblock für fortlaufende Speicherung der Adresse
  MACVor9Min = MACVor8Min;
  MACVor8Min = MACVor7Min;
  MACVor7Min = MACVor6Min;
  MACVor6Min = MACVor5Min;
  MACVor5Min = MACVor4Min;
  MACVor4Min = MACVor3Min;
  MACVor3Min = MACVor2Min;
  MACVor2Min = MACVor1Min;
  MACVor1Min = MACJetzt;
  MACJetzt = MACAktuell;

  if (advertisedDevice.haveServiceUUID())
  {
  Serial.printf("UUID: %s ", advertisedDevice.getServiceUUID().toString().c_str());

  }
  //if (advertisedDevice.getAddress().equals(*pServerAddress) & advertisedDevice.getRSSI() > MinRSSI)  // ibeacon Adresse Vergleichen
  //if (advertisedDevice.haveServiceUUID() && advertisedDevice.isAdvertisingService(cstring) & advertisedDevice.getRSSI() > MinRSSI)

  /////////////////////////////////////////////////////////////////Scannen nach Handy UUID's//////////////////////////////////////////////////////////////////////////////////////////////////////////

  if (advertisedDevice.getAddress().equals(*pServerAddress3) & advertisedDevice.getRSSI() > rssiibeacon)
  //if (advertisedDevice.haveServiceUUID() && advertisedDevice.getServiceUUID().equals(UUID2)& advertisedDevice.getRSSI() > MinRSSI)
  //if (advertisedDevice.haveServiceUUID() && advertisedDevice.getServiceUUID().equals(SWUUID)& advertisedDevice.getRSSI() > MinRSSI)

  {
  Serial.println(" Überwachte Adresse gefunden");                         // wenn überwache Adresse gefunden wurde
  digitalWrite (RelaisPin, !active_low);                        // Relais Einschalten
  Serial.println("Erfasse Schaltung zum Aufschließen !");
  TuerAUFUUID1 = 1;
  Anwesend = 1;

  VerzoegerungZaeler = 0;                                       // Ausschaltverzögerung zurücksetzen
  advertisedDevice.getScan()->stop();                           // Scanvorgang beenden
  } // Found our server

  else
  {
  TuerAUFUUID1 = 0;
  TuerAUFSWUUID = 0;
  Anwesend = 0;
  }

  if (advertisedDevice.getAddress().equals(*pServerAddress4) & advertisedDevice.getRSSI() > rssiibeacon)
  //if (advertisedDevice.haveServiceUUID() && advertisedDevice.getServiceUUID().equals(UUID2)& advertisedDevice.getRSSI() > MinRSSI)
  //if (advertisedDevice.haveServiceUUID() && advertisedDevice.getServiceUUID().equals(SWUUID)& advertisedDevice.getRSSI() > MinRSSI)

  {
  Serial.println(" Überwachte Adresse gefunden");                         // wenn überwache Adresse gefunden wurde
  digitalWrite (RelaisPin, !active_low);                        // Relais Einschalten
  Serial.println("Erfasse Schaltung zum Aufschließen !");
  TuerAUFUUID1 = 1;
  //TuerAUFSWUUID = 0;

  VerzoegerungZaeler = 0;                                       // Ausschaltverzögerung zurücksetzen
  advertisedDevice.getScan()->stop();                           // Scanvorgang beenden
  } // Found our server

  else
  {
  //TuerAUFUUID1 = 0;
  //TuerAUFSWUUID = 0;
  }

  //////////////////////////////////////////////Scannen nach G -Tag's mittels MAC - Adresse////////////////////////////////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////Tag One///////////////////////////////////////////////////////////////////////////////////////////////////////////
  if (advertisedDevice.getAddress().equals(*pServerAddress) & advertisedDevice.getRSSI() > rssimac1)    // ibeacon Adresse Vergleichen
  {
  Serial.println(" Überwachte MAC - Adresse Tag 1 gefunden");         // wenn überwache Adresse gefunden wurde
  digitalWrite (RelaisPin, !active_low);                        // Relais Einschalten
  Serial.println("Erfasse Schaltung zum Aufschließen von Tag 1 !");
  TuerAUFUUID1 = 1;
  Anwesend = 1;
  VerzoegerungZaeler = 0;                                       // Ausschaltverzögerung zurücksetzen
  advertisedDevice.getScan()->stop();                           // Scanvorgang beenden
  }
  else
  {
  TuerAUFUUID1 = 0;
  TuerAUFSWUUID = 0;
  Anwesend = 0;
  }

  ///////////////////////////////////////////////////////////Tag Two///////////////////////////////////////////////////////////////////////////////////////////////////////////

  if (advertisedDevice.getAddress().equals(*pServerAddress2) & advertisedDevice.getRSSI() > rssimac2)    // ibeacon Adresse Vergleichen
  {
  Serial.println(" Überwachte MAC - Adresse Tag 2 gefunden");         // wenn überwache Adresse gefunden wurde
  digitalWrite (RelaisPin, !active_low);                        // Relais Einschalten
  Serial.println("Erfasse Schaltung zum Aufschließen von Tag 2 !");
  TuerAUFUUID1 = 1;
  Anwesend = 1;
  VerzoegerungZaeler = 0;                                       // Ausschaltverzögerung zurücksetzen
  advertisedDevice.getScan()->stop();                           // Scanvorgang beenden
  }

  else
  {
  // TuerAUFUUID1 = 0;
  // TuerAUFSWUUID = 0;
  Anwesend = 0;
  }

  //////////////////////////////////////////////////////Scannen nach SmartWatch UUID/////////////////////////////////////////////////////////////////////////////

  if (advertisedDevice.getAddress().equals(*pServerAddress5) & advertisedDevice.getRSSI() > rssiibeacon)    // ibeacon Adresse Vergleichen

  {
  Serial.println("Zweite überwachte Adresse gefunden");                         // wenn überwache Adresse gefunden wurde
  digitalWrite (RelaisPin, !active_low);                        // Relais Einschalten
  Serial.println("Erfasse Schaltung zum Aufschließen !");
  TuerAUFSWUUID = 1;
  //TuerAUFUUID1 = 0;

  VerzoegerungZaeler = 0;                                       // Ausschaltverzögerung zurücksetzen
  advertisedDevice.getScan()->stop();                           // Scanvorgang beenden
  } // Found our server

  else
  {

  }

  Serial.println("");

  }
  };
*/

void SekundenTic()  // Wird jede Sekunde ausgefüert
{
  VerzoegerungZaeler++;  // Sekundenzähler
  if (VerzoegerungZaeler >= Verzoegerung) digitalWrite (RelaisPin, active_low); // Wenn Verzögerungszeit erreicht wurde Auschalten
}

//#################################################################SETUP##########################################################################################################

void setup() {
  Serial.begin(115200);
  DEBUG_B(115200);
  DEBUG_F("\nSketchname: %s\nBuild: %s\t\tIDE: %d.%d.%d\n\n", __FILE__, __TIMESTAMP__, ARDUINO / 10000, ARDUINO % 10000 / 100, ARDUINO % 100 / 10 ? ARDUINO % 100 : ARDUINO % 10);
  // spiffs();
  // admin();
  //Connect();
  //individualButton();
  //  setupTime();
  //  espboardLed();
  //  onboardLed();
  //  bme280();
  //  dht22();                      // Die Tabs die du nutzen möchtest, musst du Einkommentieren
  //  bh1750();
  //  setupSchaltUhr();

 

  ///////////////////////////////////////////////ConfigManager - Block///////////////////////////////////////////////////////////////////////////////////

  meta.version = 3;

  // Setup config manager
  configManager.setAPName("BTScanner");
  configManager.setAPFilename("/index.html");

  // Settings variables
  configManager.addParameter("tageins_name", config.tageins_name, 32);
  configManager.addParameter("tagzwei_name", config.tagzwei_name, 32);
  configManager.addParameter("uuideins_name", config.uuideins_name, 50);
  configManager.addParameter("uuidzwei_name", config.uuidzwei_name, 50);
  configManager.addParameter("rssi_werttageins", config.rssi_werttageins, 4);
  configManager.addParameter("rssi_werttagzwei", config.rssi_werttagzwei, 4);
  configManager.addParameter("rssi_wertibeacon", config.rssi_wertibeacon, 4);
  configManager.addParameter("webhook_ein", config.webhook_ein, 40);
  configManager.addParameter("webhook_aus", config.webhook_aus, 40);
  configManager.addParameter("led", &config.led);
  configManager.addParameter("enabled", &config.enabled);

  // Meta Settings
  configManager.addParameter("version", &meta.version, get);

  // Init Callbacks
  configManager.setAPCallback(APCallback);
  configManager.setAPICallback(APICallback);

  configManager.begin(config);

  pinMode (LEDGruen, OUTPUT);
  pinMode (LEDRot, OUTPUT);
  pinMode (LEDWeiss, OUTPUT);
  pinMode (Buzzer, OUTPUT);

  ///Hilfsschalter wird in Grundstellung geschaltet//////////////////////////////////////
  Hilfsschalter = 0;

  ArduinoOTA.onStart([]() {
    //save();                       //Einkommentieren wenn Werte vor dem Update gesichert werden sollen
  });
  ArduinoOTA.begin();
  timeClient.begin();
  AktuelleZeit = (timeClient.getHours() + 1);
  server.begin();
  DEBUG_P("HTTP Server gestartet\n\n");

  ///////////////////////////////////Codeblock umwandlung der Variablenwerte vom ConfigManager -> BLE-Scanner///////////////////////////////////////////
  String macad1 = String(mac1);
  String macad2 = String(mac2);
  String ibeaconid1 = String(ibeacon1);
  String ibeaconid2 = String(ibeacon2);
  //String tageinsrssi = String(rssimac1);
  //String tagzweirssi = String(rssimac2);
  String whein = String(WebhookEin);
  String whaus = String(WebhookAus);
  
  //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  Serial.println("Starte BLE Scanner");

  Serial.print("Metadata :");
  Serial.println(version);
  Serial.println("-------------------------------------");
 
  pServerAddress = new BLEAddress(macad1.c_str());
  pServerAddress2 = new BLEAddress(macad2.c_str());
  pServerAddress3 = new BLEAddress(ibeaconid1.c_str());
  pServerAddress4 = new BLEAddress(ibeaconid2.c_str());
  pServerAddress5 = new BLEAddress(IDadresseSW.c_str());
  BLEDevice::init("");
  
  
 
}

/*
  void Startnullung()    //Shelly wird ausgeschaltet - Grundstellung zum Start
  {
  HTTPClient http;
  Serial.println("Schalte Shelly aus...");
  http.begin(WebhookAus);                                            //Specify the URL
  int httpCode = http.GET();                                        //Make the request
  }
*/

//#################################################################LOOP######################################################################################

void loop() {

  configManager.loop();   // Um das der Webseitenaufbau der HTML - Datei sauber erfolgen kann, kein delay im Loop einbauen. Besser Millis !!.
  server.handleClient();
  timeClient.update();
  //if (millis() < 0x2FFF || millis() > 0xFFFFF0FF) runtime();  // Auskommentieren falls du den Admin Tab nicht nutzen möchtest

  
  //String tageinsrssi = String(rssimac1);
  //int zahl = atoi(rssimac1);
  //zahl = MACAktuell;
  //String tagzweirssi = String(rssimac2);
  

  Serial.print("MAC von G-Tag 1 :");
  Serial.println(mac1);
  Serial.println("-------------------------------------");
  Serial.print("MAC von G-Tag 2 :");
  Serial.println(mac2);
  Serial.println("-------------------------------------");
  Serial.print("UUID von iBeacon 1 :");
  Serial.println(ibeacon1);
  Serial.println("-------------------------------------");
  Serial.print("UUID von iBeacon 2 :");
  Serial.println(ibeacon2);
  Serial.println("-------------------------------------");
  Serial.print("Schaltentfernung G-Tag 1 :");
  //Serial.println(zahl);
  /*Serial.println("-------------------------------------");
  Serial.print("Schaltentfernung G-Tag 2 :");
  Serial.println(rssimac2);
  Serial.println("-------------------------------------");
  Serial.print("Schaltentfernung iBeacons :");
  Serial.println(rssiibeacon);
*/Serial.println("-------------------------------------");
  Serial.print("Webhook - Einschaltbefehl :");
  Serial.println(WebhookEin);
  Serial.println("-------------------------------------");
  Serial.print("Webhook - Ausschaltbefehl :");
  Serial.println(WebhookAus);
  Serial.println("-------------------------------------");

  ///////////////////////////////////////////Code - Block ConfigManager//////////////////////////////////
  unsigned long currentMillis = millis();

/*
  class MyAdvertisedDeviceCallbacks: public BLEAdvertisedDeviceCallbacks
  {
      void onResult(BLEAdvertisedDevice advertisedDevice) // passiert wenn BLE Device ( beacon ) gefunden wurde
      {

        Serial.print("iBeacon gefunden : ");
        Serial.print(advertisedDevice.toString().c_str()); // ibeacon Adresse anzeigen
        Serial.printf("   RSSI: %d ", advertisedDevice.getRSSI());
        Serial.println("---------------------------------");

        if (advertisedDevice.getAddress().equals(*pServerAddress)& advertisedDevice.getRSSI() > zahl)    // ibeacon Adresse Vergleichen
        {
          Serial.println(" Überwachte MAC - Adresse Tag 1 gefunden");         // wenn überwache Adresse gefunden wurde

        }
      }
  };

*/

  if (currentMillis - previousMillis > interval) {
    previousMillis = currentMillis;

    pBLEScan = BLEDevice::getScan(); //create new scan
    pBLEScan->setAdvertisedDeviceCallbacks(new MyAdvertisedDeviceCallbacks());
    pBLEScan->setActiveScan(true); //active scan uses more power, but get results faster
    Tic.attach( 1, SekundenTic);

    pBLEScan->start(scanTime);

  }

  ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  ///////////////////////HTTP - Update - Block///////////////////////////////////////////////////////////////////

  if ((timeClient.getMinutes() == 30) && (timeClient.getSeconds() >= 00) and (timeClient.getSeconds() <= 05))   //Prüfe immer um halb auf Updates
  {
    Serial.println();
    Serial.println("Prüfe auf HTTP - Update...");
    // ESPUpdate();
    delay(1000);
  }

  /////////////////////////////////////Überwachung WiFi - Verbindung////////////////////////////////////////

  //Netzwerküberwachung des ESP32
  if
  (WiFi.status() == WL_CONNECTED) {
    //digitalWrite(LEDGruen, HIGH);
  }

  else

  {
    digitalWrite(LEDGruen, HIGH);
    delay(100);
    digitalWrite(LEDGruen, LOW);
    delay(100);
    digitalWrite(LEDGruen, HIGH);
    delay(100);
    digitalWrite(LEDGruen, LOW);
    delay(100);
    digitalWrite(LEDRot, HIGH);
    Serial.println("Netzwerk nicht in Reichweite !");
    Serial.println("Verbindung wird aufgebaut...");
    WiFi.reconnect();
    delay(3000);
    digitalWrite(LEDRot, LOW);
    digitalWrite(LEDGruen, HIGH);
  }

  ///////////////////////////////INFO //////////////////////////////////////////

  Serial.print("Aktuelle Minute :");
  Serial.println(timeClient.getMinutes());
  Serial.println("XXXXXXXXXXXXXXXXXXXXX");
  Serial.print("Aktuelle Sekunde :");
  Serial.println(timeClient.getSeconds());

  pBLEScan->clearResults();   // Buffer wird gelöscht, um Speicher frei zu geben

}`

**Comment by nrwiersma** [comment] 2020-11-11 15:58
The problem is the same as last time. When you set a viariable it will not be automatically updated when the config value changes, it takes that value until updated. So when in the start you set `zahl` it is `0` as it should be. It is then never updated. It might be possible that `rssimac1` will be updated as it is a pointer and we use the same memory.

In general it is best to use `config.<something>` directly in your function rather then making global variables.

**Comment by Stargazer32584** [comment] 2020-11-11 16:25
Hi,

thank you for your answer. 
So, you said, it is better to put the `config.<something>` directly in the funktion ?

Is it so right, for example ?



class MyAdvertisedDeviceCallbacks: public BLEAdvertisedDeviceCallbacks
  {
      void onResult(BLEAdvertisedDevice advertisedDevice) // passiert wenn BLE Device ( beacon ) gefunden wurde
      {
        char* rssimac1 = config.rssi_werttageins;
        int zahl = atoi(rssimac1);
        Serial.print("iBeacon gefunden : ");
        Serial.print(advertisedDevice.toString().c_str()); // ibeacon Adresse anzeigen
        Serial.printf("   RSSI: %d ", advertisedDevice.getRSSI());
        Serial.println("---------------------------------");


        if (advertisedDevice.getAddress().equals(*pServerAddress)& advertisedDevice.getRSSI() > zahl)    // ibeacon Adresse Vergleichen
        {
          Serial.println(" Überwachte MAC - Adresse Tag 1 gefunden");         // wenn überwache Adresse gefunden wurde

        }
      }
  };


Thank you...

André

**Comment by nrwiersma** [comment] 2020-11-11 16:28
Yes, that is correct. This will give you the value at the time it is needed.

**Comment by Stargazer32584** [comment] 2020-11-11 18:46
Hi,

you made my day, again :-D !

Thank you very much for your support !!

Best regards and a good evening..

André

**Comment by nrwiersma** [comment] 2020-11-11 18:47
No worries. I will close this issue. Feel free to reopen if needed.

**Closed by nrwiersma** 2020-11-11 18:47 UTC
